project/server/user/forms.py
# project/server/user/forms.py


from flask_wtf import Form
from wtforms import StringField, PasswordField, FileField
from wtforms.validators import DataRequired, Email, Length, EqualTo


class LoginForm(Form):
    email = StringField('Email Address', [DataRequired(), Email()])
    password = PasswordField('Password', [DataRequired()])


class RegisterForm(Form):
    email = StringField(
        'Email Address',
        validators=[DataRequired(), Email(message=None), Length(min=6, max=40)])
    password = PasswordField(
        'Password',
        validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        'Confirm password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )

class UploadForm(Form):
    file = FileField('', validators=[DataRequired()])

class ConnectForm(Form):
    host = StringField('Host', [DataRequired()])
    user = StringField('User')
    password = PasswordField('Password')
    database = StringField('Database', [DataRequired()])
    table = StringField('Table', [DataRequired()])

project/server/user/__init__.py
# project/server/user/__init__.py

project/server/user/views.py
# project/server/user/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint, url_for, \
    redirect, flash, request, session
from flask_login import login_user, logout_user, login_required

from project.server import bcrypt, db
from project.server.models import User, Data, prevod, Tabulka
from project.server.user.forms import LoginForm, RegisterForm, UploadForm, ConnectForm
from .database import DatabaseConnection
from sqlalchemy import update, insert

import xml.etree.ElementTree as ET
import pymysql
import pymysql.cursors
import tempfile
import os

################
#### config ####
################

user_blueprint = Blueprint('user', __name__, )


################
#### routes ####
################

@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            password=form.password.data
        )
        db.session.add(user)
        db.session.commit()

        login_user(user)

        flash('Thank you for registering.', 'success')
        return redirect(url_for("user.home"))

    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            login_user(user)
            flash('You are logged in. Welcome!', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Invalid email and/or password.', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', title='Please Login', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out. Bye!', 'success')
    return redirect(url_for('main.home'))


@user_blueprint.route('/xmlparser', methods=['POST', 'GET'])
@login_required
def xmlparser():
    try:
        host = session['db_host']
        session.pop('db_host', None)
        user = session['db_user']
        session.pop('db_user', None)
        password = session['db_password']
        session.pop('db_password', None)
        db = session['db_database']
        session.pop('db_database', None)

        destination = session['file']
        session.pop('file', None)
        file = open(destination, "r")

        tree = ET.parse(file)
        root = tree.getroot()

        tagy = []
        radky = 0
        for child in root:
            sloupce = 0
            for tag in child:
                if root[radky][sloupce].tag not in tagy:
                    tagy.append(prevod(root[radky][sloupce].tag))
                sloupce += 1
            radky += 1

        data = Data(radky)

        radkyX = 0
        attributy1 = 0
        attributy2 = 0

        for child in root:
            sloupceY = 0
            if child.attrib != "{}":
                for key in child.attrib:
                    if not key in tagy:
                        tagy.append(key)
                        attributy1 += 1
                    data.setData(radkyX, key, child.attrib[key])
            for tag in child:
                data.setData(radkyX, root[radkyX][sloupceY].tag, root[radkyX][sloupceY].text)
                if tag.attrib != "{}":
                    for key in tag.attrib:
                        if not key in tagy:
                            tagy.append(key)
                            attributy2 += 1
                        data.setData(radkyX, key, tag.attrib[key])
                sloupceY += 1
            radkyX += 1

        """ sql = 'INSERT INTO `' + prevod(session['db_table']) + '` ('
        for tag in tagy:
            if request.form[tag] != "":
                if sql == 'INSERT INTO `' + prevod(session['db_table']) + '` (':
                    sql += prevod(request.form[tag])
                else:
                    sql += ',' + prevod(request.form[tag])

        session.pop('db_table', None)
        sql += ') VALUES '
        for x in range(0,radky):
            prvni = True
            if x == 0:
                sql += "("
            else:
                sql += ",("
            for tag in tagy:
                if request.form[tag] != "":
                    if prvni is True:
                        sql += "'" + prevod(data.getData(x,tag)) + "'"
                        prvni = False
                    else:
                        sql += ",'" + prevod(data.getData(x,tag)) + "'"
            sql += ")"
        sql += ";" """

        tabulka = Tabulka(session['db_table'])
        session.pop('db_table', None)
        database = DatabaseConnection('mysql://'+user+':'+password+'@'+host+'/'+db)
        #database.session.query(tabulka).\
        insert(tabulka).values(nazev=data.getData(0,'title'))
        """ conn = pymysql.connect(host=host, user=user, password=password, db=db, cursorclass=pymysql.cursors.DictCursor)
        a = conn.cursor()
        file.close()
        os.remove(destination)
        a.execute(sql)
        conn.commit() """
        flash('Success', 'success')
        return render_template('main/home.html')
    except:
        flash('Unexpected error', 'danger')

    return redirect(url_for("user.upload"))


@user_blueprint.route('/upload', methods=['POST', 'GET'])
@login_required
def upload():
    if 'db_host' not in session:
        form = ConnectForm(request.form)
        return render_template('user/connect.html',form=form)
    form = UploadForm(request.form)
    return render_template('user/upload.html',form=form)

@user_blueprint.route('/connect', methods=['POST', 'GET'])
@login_required
def connect():
    session['db_host'] = request.form['host']
    session['db_user'] = request.form['user']
    session['db_password'] = request.form['password']
    session['db_database'] = request.form['database']
    session['db_table'] = request.form['table']
    return redirect(url_for("user.upload"))


@user_blueprint.route('/process', methods=['POST', 'GET'])
@login_required
def process():
    if 'file' not in request.files:
        flash('No file part', 'danger')
        return redirect(url_for("user.upload"))

    file = request.files['file']
    if file.filename == '':
        flash('No selected file', 'danger')
        return redirect(url_for("user.upload"))

    if file.filename.rsplit('.', 1)[1].lower() not in ['xml']:
        flash('This is not .xml file', 'danger')
        return redirect(url_for("user.upload"))

    try:
        filename = file.filename
        target = tempfile.gettempdir()
        destination = "/".join([target, filename])
        file.save(destination)
        session['file'] = destination
        file = open(destination,"r")

        tree = ET.parse(file)
        root = tree.getroot()

        tagy = []
        radky = 0
        for child in root:
            sloupce = 0
            for tag in child:
                if root[radky][sloupce].tag not in tagy:
                    tagy.append(root[radky][sloupce].tag)
                sloupce += 1
            radky += 1

        data = Data(radky)

        radkyX = 0
        attributy1 = 0
        attributy2 = 0
        for child in root:
            sloupceY = 0
            if child.attrib != "{}":
                for key in child.attrib:
                    if not key in tagy:
                        tagy.append(key)
                        attributy1 += 1
                    data.setData(radkyX, key, child.attrib[key])
            for tag in child:
                data.setData(radkyX, root[radkyX][sloupceY].tag, root[radkyX][sloupceY].text)
                if tag.attrib != "{}":
                    for key in tag.attrib:
                        if not key in tagy:
                            tagy.append(key)
                            attributy2 += 1
                        data.setData(radkyX, key, tag.attrib[key])
                sloupceY += 1
            radkyX += 1
            sloupce = sloupceY + attributy1 + attributy2

        conn = pymysql.connect(host = session['db_host'], user = session['db_user'], password = session['db_password'],
                               db=session['db_database'], cursorclass=pymysql.cursors.DictCursor)
        a = conn.cursor()
        sql = "SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = '" + prevod(session['db_table']) + "'"
        a.execute(sql)
        result = a.fetchall()
        db_tagy = []
        for column in result:
            db_tagy.append(column['COLUMN_NAME'])
    except:
        session.pop('db_host', None)
        session.pop('db_user', None)
        session.pop('db_password', None)
        session.pop('db_database', None)
        session.pop('db_table', None)
        flash('Unexpected error', 'danger')
        return redirect(url_for("user.upload"))

    return render_template('user/xmlparser.html', data=data, tagy=tagy, db_tagy=db_tagy, sloupce=sloupce)

project/client/templates/user/connect.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

  <header class="content-header">
    <h1>Connect to database</h1>
  </header>

  <br>


  <form class="form" role="form" method="post" action="{{ url_for('user.connect') }}">

    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}


    <div class="col-lg-4 col-sm-4">
      {{ wtf.form_field(form.host) }}
      {{ wtf.form_field(form.user) }}
      {{ wtf.form_field(form.password) }}
      {{ wtf.form_field(form.database) }}
      {{ wtf.form_field(form.table) }}

      <button class="btn btn-primary" type="submit">Connect</button>
    </div>
  </form>


{% endblock content %}

project/client/templates/user/login.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

  <header class="content-header">
    <h1>Please login</h1>
  </header>

  <br>


  <form class="form" role="form" method="post" action="">

    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}


    <div class="col-lg-4 col-sm-4">

      {{ wtf.form_field(form.email) }}
      {{ wtf.form_field(form.password) }}

      <button class="btn btn-success" type="submit">Sign In!</button>
      <br><br>
      <p>Need to <a href="{{ url_for('user.register') }}">Register</a>?</p>
    </div>

  </form>


{% endblock content %}

project/client/templates/user/members.html
{% extends "_base.html" %}
{% block content %}
  <h1>Welcome, <em>{{ current_user.email }}</em>!</h1>
  <h3>This is the members-only page.</h3>
{% endblock %}

project/client/templates/user/register.html
{% extends '_base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

  <header class="content-header">
    <h1>Please Register</h1>
  </header>

  <br>


  <form class="form" role="form" method="post" action="">

    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}


    <div class="col-lg-4 col-sm-4">

      {{ wtf.form_field(form.email) }}
      {{ wtf.form_field(form.password) }}
      {{ wtf.form_field(form.confirm) }}

      <button class="btn btn-success" type="submit">Register!</button>
      <br><br>
      <p>Already have an account? <a href="{{ url_for('user.login') }}">Sign in</a>.</p>

    </div>

  </form>


{% endblock content %}

project/client/templates/user/select.html
{% extends "_base.html" %}
{% block content %}
<script>
            $(function() {
              // We can attach the `fileselect` event to all file inputs on the page
              $(document).on('change', ':file', function() {
                var input = $(this),
                    numFiles = input.get(0).files ? input.get(0).files.length : 1,
                    label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
                input.trigger('fileselect', [numFiles, label]);
              });
              // We can watch for our custom `fileselect` event like this
              $(document).ready( function() {
                  $(':file').on('fileselect', function(event, numFiles, label) {
                      var input = $(this).parents('.input-group').find(':text'),
                          log = numFiles > 1 ? numFiles + ' files selected' : label;

                      if( input.length ) {
                          input.val(log);
                      } else {
                          if( log ) alert(log);
                      }
                  });
              });
            });
</script>
<h1>Welcome, <em>{{ current_user.email }}</em>!</h1>
<form id=upload-form action="{{ url_for('user.select_process') }}" method=post enctype=multipart/form-data>
    <div class="input-group">
        <label class="input-group-btn">
                <span class="btn btn-primary">
                    Browse&hellip; <input type=file name=file id=file style="display: none;">
                </span>
        </label>
        <input type="text" class="form-control" readonly>
    </div>
    <input class="btn btn-basic" type=submit value=Upload>
</form>
{% endblock %}

project/client/templates/user/upload.html
{% extends "_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

<script>
            $(function() {
              // We can attach the `fileselect` event to all file inputs on the page
              $(document).on('change', ':file', function() {
                var input = $(this),
                    numFiles = input.get(0).files ? input.get(0).files.length : 1,
                    label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
                input.trigger('fileselect', [numFiles, label]);
              });
              // We can watch for our custom `fileselect` event like this
              $(document).ready( function() {
                  $(':file').on('fileselect', function(event, numFiles, label) {
                      var input = $(this).parents('.input-group').find(':text'),
                          log = numFiles > 1 ? numFiles + ' files selected' : label;
                      if( input.length ) {
                          input.val(log);
                      } else {
                          if( log ) alert(log);
                      }
                  });
              });
              $(document).ready( function() {
                $('.form-group').attr("style", "display:none");;
              });
            });
</script>

<header class="content-header">
    <h1>Select XML file</h1>
</header>
<br>
<form class="form" role="form" action="{{ url_for('user.process') }}" method=post enctype=multipart/form-data>
    {{ form.csrf_token }}
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}


    <div class="input-group">
        <label class="input-group-btn">
                <span class="btn btn-primary">
                    Browse&hellip; {{ wtf.form_field(form.file) }}
                </span>
        </label>
        <input type="text" class="form-control" readonly>
    </div>
    <button class="btn btn-basic" type="submit">Upload</button>
</form>
{% endblock %}

project/client/templates/user/xmlparser.html
{% extends "_base.html" %}
{% block content %}
<header class="content-header">
    <h1>Import setting</h1>
</header>
<br>
<form id="form" role="form" class="form" action="{{ url_for('user.xmlparser') }}" method=post>
    <table class="table-bordered">
        <tr>
            <th>Tag</th>
            <th>Value</th>
            <th>Column</th>
        </tr>
        {% for x in range(0,sloupce) %}
        <tr>
            <td>{{ tagy[x] }}</td>
            <td>{{ data.getData(0,tagy[x]) }}</td>
            <td>
                <select name={{tagy[x]}} form="form">
                    <option value="" selected></option>
                    {% for tag in db_tagy %}
                    <option value="{{ tag }}">{{ tag }}</option>
                    {% endfor %}
                </select>
            </td>
        </tr>
        {% endfor %}
        <tr><td colspan="3"><input class="btn btn-lg btn-primary btn-block" type=submit value=Submit></td></tr>
    </table>
</form>
{% endblock %}